config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  root to: 'home#index'

  
  match '/auth/:provider/callback' => 'sessions#create', via: :get

  match '/signout' => 'sessions#destroy', :as => :signout,  via: :get

  match '/signin' => 'sessions#new', :as => :signin, via: :get
  
  match '/loggedin' => 'sessions#loggedin', as: :loggedin, via: :get
  match '/loggedout' => 'sessions#loggedout', as: :loggedout, via: :get
  
end

app/models/user.rb
class User < ActiveRecord::Base

# from https://github.com/ralphos/omniauth-facebook-example
  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth['provider']
      user.uid = auth['uid']
      if auth['info']
        user.name = auth['info']['name'] || ""
        user.email = auth['info']['email'] || ""
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
 def create
   auth = request.env["omniauth.auth"]
   puts "info keys:  #{auth['info'].keys.join(',')}"
   user = User.where(:provider => auth['provider'], 
                     :uid => auth['uid']).first || User.create_with_omniauth(auth)
   session[:user_id] = user.id
   # redirect to clean up URL in browser window
   # redirect_to root_url, :notice => "Signed in!"
   redirect_to "/loggedin"
 end

 def new
   redirect_to '/auth/cas3'
 end

 def destroy
   reset_session
   redirect_to root_url, notice => 'Signed out'
 end
 
 def loggedin
   @user=  User.find(session[:user_id])
 end
 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/home/index.html.erb
<h1>Homepage</h1>

 <ul>
 <% flash.each do |key, msg| %>
   <%= content_tag :li, msg, id: key %>
 <% end %>
 </ul>

 <p><%= link_to 'Sign in CAS', signin_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CAS Server</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>
</body>
</html>